code_name = [
    "Abu Dhabi",
    "Agena",
    "Albany",
    "Allendale",
    "Arrandale",
    "Athens",
    "Banias",
    "Barcelona",
    "Barton",
    "Bay Trail-I",
    "Bay Trail-M",
    "Bay Trail-T",
    "Bloomfield",
    "Brisbane",
    "Bristol Ridge",
    "Broadwell",
    "Broadwell-DT",
    "Broadwell-E",
    "Broadwell-U",
    "Broadwell-Y",
    "Callisto",
    "Cascade Lake-AP",
    "Cascade Lake-SP",
    "Cedar Mill",
    "Cedarview",
    "Centerton",
    "Clarkdale",
    "Clawhammer",
    "Clovertrail",
    "Cloverview",
    "Coffee Lake",
    "Coffee Lake-H",
    "Coffee Lake-S",
    "Coffee Lake-U",
    "Conroe",
    "Conroe XE",
    "Conroe-CL",
    "Conroe-L",
    "Coppermine",
    "Coppermine T",
    "Cranford",
    "Crystalwell",
    "Delhi",
    "Dempsey",
    "Deneb",
    "Denmark",
    "Desna",
    "Diamondville",
    "Dothan",
    "Egypt",
    "Gainestown",
    "Gallatin",
    "Georgetown",
    "Gladden",
    "Griffin",
    "Gulftown",
    "Haswell",
    "Haswell-E",
    "Haswell-EX",
    "Haswell-ULT",
    "Haswell-WS",
    "Heka",
    "Hondo",
    "Interlagos",
    "Irwindale",
    "Italy",
    "Ivy Bridge",
    "Ivy Bridge-E",
    "Ivy Bridge-EN",
    "Ivy Bridge-EP",
    "Jasper Forest",
    "Kabini",
    "Kaby Lake",
    "Kaby Lake G",
    "Kaby Lake-DT",
    "Kaby Lake-H",
    "Kaby Lake-R",
    "Kaby Lake-X",
    "Kaveri",
    "Kentsfield",
    "Knights Corner",
    "Knights Ferry",
    "Knights Landing",
    "Knights Mill",
    "Kuma",
    "Kyoto",
    "Lancaster",
    "Lima",
    "Lincroft",
    "Llano",
    "Lynnfield",
    "Magny-Cours",
    "Manchester",
    "Manila",
    "Merom",
    "Merom XE",
    "Merom-L",
    "NewCastle",
    "Newark",
    "Nocona",
    "Northwood",
    "Odessa",
    "Ontario",
    "Orleans",
    "Palermo",
    "Palomino",
    "Paris",
    "Paxville",
    "Penryn",
    "Penryn QC",
    "Penryn QC XE",
    "Penryn XE",
    "Penryn-L",
    "Penwell",
    "Picasso",
    "Pineview",
    "Potomac",
    "Prescott",
    "Presler",
    "Prestonia",
    "Propus",
    "Rana",
    "Raven Ridge",
    "Raven Ridge 2",
    "Regor",
    "Richland",
    "Roma",
    "San Diego",
    "Sandy Bridge",
    "Sandy Bridge-E",
    "Sandy Bridge-EN",
    "Sandy Bridge-EP",
    "Sargas",
    "Seattle",
    "Seoul",
    "Silverthorne",
    "Skylake",
    "Skylake-H",
    "Skylake-S",
    "Skylake-SP",
    "Skylake-W",
    "Skylake-X",
    "SledgeHammer",
    "Smithfield",
    "Sodaville",
    "Sonora",
    "Sparta",
    "Stealey",
    "Stellarton",
    "Steppe Eagle",
    "Stoney Ridge",
    "Temash",
    "Thoroughbred",
    "Thorton",
    "Thuban",
    "Thunderbird",
    "Thunderbird B",
    "Thunderbird C",
    "Toledo",
    "Toliman",
    "Trinity",
    "Troy",
    "Tualatin",
    "Tulsa",
    "Tunnel Creek",
    "Venice",
    "Venus",
    "Vishera",
    "Westmere-EP",
    "Westmere-EX",
    "Whiskey Lake-U",
    "Willamette",
    "Winchester",
    "Windsor",
    "Wolfdale",
    "Woodcrest",
    "Yonah",
    "Yorkfield",
    "Zacate",
    "Zambezi",
    "Zen",
    "Zen 2",
    "Zosma",
]
